version: '3'

services:
  http-server:
    image: sebp/lighttpd
    container_name: 'mineiro.info-http'
    tty: true
    volumes:
      - ./public:/var/www/localhost/htdocs
    ports:
      - 8080:80
